class MPU6050
  type accel_range = :g2 | :g4 | :g8 | :g16
  type gyro_range = :dps250 | :dps500 | :dps1000 | :dps2000

  ADDRESS: Integer
  ALTERNATE_ADDRESS: Integer

  attr_reader address: Integer
  attr_reader accel_range: accel_range
  attr_reader gyro_range: gyro_range

  def initialize: (
    i2c: I2C,
    ?address: Integer,
    ?accel_range: accel_range,
    ?gyro_range: gyro_range
  ) -> void
  def connected?: () -> bool
  def who_am_i: () -> Integer
  def accel_range=: (accel_range) -> accel_range
  def gyro_range=: (gyro_range) -> gyro_range
  def read_raw: () -> Hash[Symbol, untyped]
  def read: () -> Hash[Symbol, untyped]
  def motion6_raw: () -> Array[Integer]
  def motion6: () -> Array[Float]
  def acceleration: () -> Array[Float]
  def gyroscope: () -> Array[Float]
  def temperature: () -> Float

  private def _decode_frame: (String frame) -> Array[Integer]

  class DeviceNotFoundError < StandardError
  end
end
